version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: linorra/infra_backend-1
    env_file: .env
    volumes:
      - static:/static_backend/
      - media:/media/
    depends_on:
      - db
  
  frontend:
    image: linorra/infra_frontend-1
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ./frontend/:/app/result_build/
      - static:/static


  gateway:
    image: linorra/infra_gateway-1
    env_file: .env
    volumes:
      - static:/static
      - media:/media/
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
