version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: linorra/infra_backend-1
    env_file: .env
    volumes:
      # - static:/app/static_django/
      - static:/static_django/
      - media:/app/media/
      - redoc:/app/docs/
    depends_on:
      - db
  
  frontend:
    env_file: .env
    image: linorra/infra_frontend-1
    command: cp -r /app/build/. /result_build/
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
    - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - redoc:/usr/share/nginx/html/api/docs/

    depends_on:
      - backend