version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: linorra/infra_backend-1
    env_file: .env
    volumes:
      - static:/static_backend/
      - media:/app/media/
      - redoc:/app/docs/
    depends_on:
      - db
  
  frontend:
    image: linorra/infra_frontend-1
    env_file: .env
    command: cp -r /app/build/. /result_build/
    volumes:
      - static:/result_build/
      # - ./frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
    - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media/
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./frontend/build:/usr/share/nginx/html/
      # - static_frontend:/static_frontend/
      # - ./docs/:/usr/share/nginx/html/api/docs/
      # - redoc:/usr/share/nginx/html/api/docs/

    depends_on:
      - backend
