# Generated by Django 3.2.3 on 2024-01-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_follow_user_is_not_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
    ]
